version: "3.7"

services:
    # image migracao
    migracao:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: migracao
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel

    # nginx
    nginxmigracao:
        image: nginx:1.25.3
        container_name: nginxmigracao
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    #rede bridge
networks:
    laravel:
        driver: bridge